# 가장 강력한 설정파일. 이곳에서 DB, JDA, Log등을 설정
# spring.io/projects/spring-boot#learn 에서 배워야한다.
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop #;MVCC=TRUE 버젼 변경으로 해당 설정 지원 x. 에러나옴!
    name: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # application 실행 시점에 보유하고 있는 테이블을 다 지우고 entity를 토대로 다시 만든다.
    properties: # hibernate 관련 설정
      hiernate:
        # show_sql: true 얘는 hibernate의 sql문을 sysout으로 찍기 때문에 버리자.
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # hibernate가 남기는 모든 sql이 로그에 디버그모드로 보인다.